### ISSUE TITLE
Able to destroy chests with items in it (Also using InfiniteChests)

### ISSUE THREAD

**Issue by TeeriaLLC** [CoderCow/Protector-Plugin#32]
People are able (When using inifnitechests, which worked perfectly fine before in 1.2.4.1) to destroy chests which contain items in it and people are ALSO (still) able to open the same chest at the same time.

Wondering if you could fix both of these issues as this plugin is greatly needed and these bugs are gamebreaking.

Thank you.

**Comment by CoderCow** [comment]
Don't have the time to test with InfiniteChests, but one of the latest commits might fix this.

**Comment by TeeriaLLC** [comment]
The issue seems to be fixed, filled chests can no longer be destroyed.
