### ISSUE TITLE
Objects of type Chest can not be protected

### ISSUE THREAD

**Issue by Gavekort** [CoderCow/Protector-Plugin#35]
Running Terraria Server v1.3.0.8 with the latest 1.3.9 build of Protector Plugin. I'm typing in /protect as a superadmin, hits the chest I want to protect and gets the message "Objects of type Chest can not be protected".

**Comment by CoderCow** [comment]
Check if the Xml element "ManuallyProtectableTiles" in your Config.xml has 21 in its tile id list.

**Comment by Gavekort** [comment]
Solved the problem. The config-file wasn't in it's correct location.
