### ISSUE TITLE
ProtectorPlugin is designed for a different Server API version (1.22) and was ignored.

### ISSUE THREAD

**Issue by wog24435** [CoderCow/Protector-Plugin#39]
tShock is still on version 1.21, not 1.22.

[Server API] Warning Plugin "Terraria.Plugins.CoderCow.Protector.ProtectorPlugin " is designed for a different Server API version (1.22) and was ignored.

**Comment by CoderCow** [comment]
You gotta use the build from an older commit, prior the version tick. Like this one: 
https://github.com/CoderCow/Protector-Plugin/tree/49cec058864bc52234e190c50acbb9b8ba8cef30/bin/Release
