### ISSUE TITLE
Own Chest Protection Limit per Player

### ISSUE THREAD

**Issue by Hiarni** [CoderCow/Protector-Plugin#41]
As the titel said - it would be very awesome if we could set limits only for chests aside of "overall protection limit".

So if you set 25 protections as maximum per player you should be able to set 6 chests as example as maximum placeable beside of the 25 "normal" protections. :+1:

**Comment by SmallSansSerif** [comment]
This would be a great feature! Please consider.

**Comment by CoderCow** [comment]
I guess the ChestLimiter is already handling this well.
Protector needs better compatibility with other plugins to make them work together properly though.
