### ISSUE TITLE
Please update on TShock.co

### ISSUE THREAD

**Issue by TeeriaLLC** [CoderCow/Protector-Plugin#44]
I'm having trouble actually building/downloading this, it'd be easier if this was added/updated on TShock.co or a simple download link provided.

Thanks again :)

**Comment by CoderCow** [comment]
Most recent build is always found here: https://github.com/CoderCow/Protector-Plugin/tree/master/bin/Release

**Comment by PixelGMS** [comment]
Can you please update this to 1.3.0.8? The plugin won't work on my server because the most recent update to this plugin was for 1.2.something. Thanks for your help! _Please email me at voidcraft@hotmail.com when you have update the plugin to 1.3.0.8, thank you!_
