### ISSUE TITLE
Can you please update this to 1.3.0.8?

### ISSUE THREAD

**Issue by PixelGMS** [CoderCow/Protector-Plugin#46]
Can you please update this to 1.3.0.8? The plugin won't work on my server because the most recent update for this plugin was for 1.2.something. Thanks for your help! _Please email me at voidcraft@hotmail.com when you have updated the plugin to 1.3.0.8, thank you!_

**Comment by CoderCow** [comment]
I guess you used the release from [here](https://github.com/CoderCow/Protector-Plugin/releases). This is not up to date as I'm not using GitHub releases anymore.

This plugin is already on 1.3.0.8 (API 1.22). The most recent build is always found here: https://github.com/CoderCow/Protector-Plugin/tree/master/bin/Release

I guess you've got auto subscribed to this issue, so you'll receive an e-mail as I post this automatically.
