### ISSUE TITLE
the type of object chest cannot be protect

### ISSUE THREAD

**Issue by diancangyun** [CoderCow/Protector-Plugin#48]
when I ues /protect and hit a chest or other object , it say this,
I like this plugin ,can you help me!

**Comment by diancangyun** [comment]
I use the 1.3.11 tshock

**Comment by CoderCow** [comment]
I guess you didn't install Protector properly.

Ensure that you have Protector's **Config.xml** and **Config.xsd** files in a **tshock/Protector** directory and also ensure that your **Config.xml** has id **21** (the tile id of chests) listed in the XML Element **ManuallyProtectableTiles**.

**Comment by diancangyun** [comment]
oh,it can use,thank you very much!
you are god people.
