### ISSUE TITLE
Unhandled exception in SaveWorld handler

### ISSUE THREAD

**Issue by Vednix** [CoderCow/Protector-Plugin#51]
2017-01-29 18:41:51 - Utils: INFO: Servidor executed: /save.
2017-01-29 18:41:52 - PluginTrace: ERROR: [Protector] Unhandled exception in SaveWorld handler:
System.ArrayTypeMismatchException: Tentativa de acesso a um elemento como um tipo incompatível com a matriz.
   em Terraria.Plugins.CoderCow.Protector.WorldMetadata.Write(String filePath)
   em Terraria.Plugins.Common.MetadataHandlerBase.WriteMetadata()
   em Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.World_SaveWorld(WorldSaveEventArgs e)

**Protector.dll compiled from source**

**Comment by CoderCow** [comment]
Do you get the same error with the prebuild dll from https://github.com/CoderCow/Protector-Plugin/tree/master/bin/Release ?

**Comment by CoderCow** [comment]
I guess this has been resolved.
