### ISSUE TITLE
[Suggestion] List all chests in the world on a table-like database for better management.

### ISSUE THREAD

**Issue by tanpro260196** [CoderCow/Protector-Plugin#55]
Can you add a command that made this plugin generate a table-like database (sqlite or excel) for every chests on the map that include:

- Chest ID
- Chest Location
- Chest Owner (if available)
- Protected/Refill status
- Chest Content
- And anything else you may think of.

About why this will be useful: 
- Let's say I found a cheater/hacker and proceed to ban him forever.
- But then I will have to deal with the aftermath, I have to find out whether he have give cheat items to anyone else in the server, and check every single chests in the World to make sure he does not throw a Last Prism in some random chest Underground.
- If I can have a table like above, searching would be a lot simpler and less painful.

**Comment by CoderCow** [comment]
Hmm... I'd rather implement a command to scan existing chests for certain items coupled with a teleport command to visit them. 
And actually, I do have a half-finished version of such a command already up my sleeve.

**Comment by tanpro260196** [comment]
That would be great. Thank you.

And I just found one more cheater. What a pain....
