### ISSUE TITLE
[Bug] Protector break History plugin

### ISSUE THREAD

**Issue by tanpro260196** [CoderCow/Protector-Plugin#56]
History Plugin no longer record tile placement once you installed Protector (any version).
History still record tile break, wall placement, tile slope, paint. But does not record tile placement.

History: https://tshock.co/xf/index.php?resources/history.154/
Lastest Version of History on Github : https://github.com/deadsurgeon42/History

**Comment by CoderCow** [comment]
This is due to the order in which hooks are registered by the plugins. Shouldn't be hard to fix.
